/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        primary: "#6366f1",
        "primary-foreground": "#ffffff",
        secondary: "#f3f3f5",
        "secondary-foreground": "#030213",
        background: "#f8fafc",
        "card-background": "#ffffff",
        foreground: "#030213",
        "muted-foreground": "#717182",
        muted: "#f1f5f9",
        accent: "#f1f5f9",
        "accent-foreground": "#030213",
        border: "rgba(0, 0, 0, 0.1)",
        input: "#ffffff",
        ring: "#6366f1",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#ffffff",
        destructive: "#d4183d",
        "destructive-foreground": "#ffffff",
        packing: "#f59e0b",
        "packing-foreground": "#ffffff",
        itinerary: "#a855f7",
        "itinerary-foreground": "#ffffff",
        journal: "#10b981",
        "journal-foreground": "#ffffff",
      },
      fontFamily: {
        racing: ["RacingSansOne", "cursive"],
        sriracha: ["Sriracha", "cursive"],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
        "4xl": "48px",
        "5xl": "64px",
      },
      borderRadius: {
        sm: "4px",
        md: "6px",
        lg: "12px",
        xl: "18px",
        "2xl": "24px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-in": "slideIn 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
};
